#in alpine this file does not exist by defualt, that's why we have to create it ourselves

# FastCGI is a protocol that lets Nginx talk to programs that generate dynamic content, like PHP.
#How it works in practice:
#User requests http://example.com/index.php
#Nginx sees .php and passes it via FastCGI to PHP-FPM
#PHP-FPM executes the script and returns HTML output
#Nginx sends that output to the user

# fastcgi-php.conf (tells php how to pass requests to php-fpm)
# we include fastcgi variables
include fastcgi_params;

#tells which files to execute, these vars are set in nginx.conf. i think the first one is the path var/www/html and the second one is the requested url so irlozano.42.fr/index.html?

#If a user visits: http://example.com/index.php
#Nginx combines $document_root + $fastcgi_script_name → /var/www/html/index.php
#
#la variable SCRIPT_FILENAME es el path completo al script a ejecutar, ruta + web (ej: /var/www/html/blog/index.php) mientras que SCRIPT_NAME es solo la parte web (/blog/index.php)
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param SCRIPT_NAME $fastcgi_script_name;